root_path: "L:/BiFuse"
train_file_list: ''
exp_path: "./experiment"
exp_freq: 30
save_path: "./save"
save_freq: 500
output_path: "./output"
incremental: False
seed: 224
metrics: ["rmse", 'log_rmse', "delta1", 'delta2', 'delta3']
# metrics: ["rmse", "mae","mre", 'rmse_log', "delta1", 'delta2', 'delta3']
#metrics: ["rmse", "mae", "delta1", 'delta2', 'delta3']
processes: 1
batch_size: 1
#batch_size: 8
epochs: 30 #total epoch number
lr: 0.0003
print_step: 30
log_step: 30
val_metric_field: ["rmse", "mae","mre"]
model_layer: 50
decoder_type: "upproj"
training_stage: 3

#output_size: (512,1024)
